/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import { r } from 'rkyv-js';

export const ArchivedBTreeMapConfig = r.struct({
  settings: r.btreeMap(r.string, r.u32),
  version: r.u32,
});

export type BTreeMapConfig = r.infer<typeof ArchivedBTreeMapConfig>;

export default ArchivedBTreeMapConfig;
