/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';
import { hashMap } from 'rkyv-js/lib/std-hash-map';

export const ArchivedHashMapData = r.struct({
  entries: hashMap(r.string, r.u32),
  name: r.string,
});

export type HashMapData = r.Infer<typeof ArchivedHashMapData>;

export default ArchivedHashMapData;
