/**
 * JS side of the JS↔Rust conformance loop.
 *
 * For every case under conformance/cases/ (generated by
 * `cargo run -p conformance --bin generate`):
 *
 * 1. decode data.bin and deep-compare against the revived canonical
 *    data.json (bigints, bytes, maps, and float bit patterns are tagged)
 * 2. re-encode the decoded value and write js.bin for the Rust verifier
 *    (`cargo run -p conformance --bin verify`)
 * 3. identical-class cases also assert byte equality right here
 */

import * as assert from 'node:assert';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import * as path from 'node:path';
import { describe, it } from 'node:test';

import type { AnyCodec } from '#src/core/codec.ts';
import * as bindings from '#conformance/cases/bindings.ts';
import { conformanceEqual, inspect, revive } from './_canonical.ts';

const CASES_DIR = path.join(import.meta.dirname, '..', 'conformance', 'cases');

interface Meta {
  case: string;
  type: string;
  codec: string;
  class: 'identical' | 'semantic';
  ordered: boolean;
}

const entries = await readdir(CASES_DIR, { withFileTypes: true });
const caseDirs = entries.filter((e) => e.isDirectory()).map((e) => e.name).sort();

describe('conformance', async () => {
  for (const name of caseDirs) {
    it(name, async () => {
      const dir = path.join(CASES_DIR, name);
      const meta = JSON.parse(await readFile(path.join(dir, 'meta.json'), 'utf-8')) as Meta;
      const codec = (bindings as Record<string, unknown>)[meta.codec] as AnyCodec | undefined;
      assert.ok(codec, `bindings.ts is missing export ${meta.codec}`);

      const data = new Uint8Array(await readFile(path.join(dir, 'data.bin')));
      const expected = revive(JSON.parse(await readFile(path.join(dir, 'data.json'), 'utf-8')));

      // 1. Rust → JS: decode matches the canonical value.
      const decoded: unknown = codec.decode(data);
      assert.ok(
        conformanceEqual(decoded, expected, meta.ordered),
        `decoded value differs from canonical data.json\ndecoded: ${inspect(decoded)}\nexpected: ${inspect(expected)}`,
      );

      // 2. JS → Rust: re-encode for the Rust verifier.
      const reencoded = codec.encode(decoded);
      await writeFile(path.join(dir, 'js.bin'), reencoded);

      // 3. Identical-class cases must already match byte-for-byte.
      if (meta.class === 'identical') {
        assert.deepStrictEqual(
          reencoded,
          data,
          'identical-class case re-encoded to different bytes',
        );
      }
    });
  }
});
