/**
 * JS side of the non-default-format conformance smoke loop.
 *
 * Each profile under conformance/formats/cases-<profile>/ is generated by a
 * standalone Rust mini-crate built with the matching rkyv format feature
 * (`cargo run --manifest-path conformance/formats/<p>/Cargo.toml -- generate`).
 * Profiles that haven't been generated are skipped.
 */

import * as assert from 'node:assert';
import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import * as path from 'node:path';
import { describe, it } from 'node:test';

import * as r from '#src/index.ts';
import { format, type RkyvFormat } from '#src/core/format.ts';
import { hashMap } from '#src/lib/hashmap.ts';
import { indexMap } from '#src/lib/indexmap.ts';

import { conformanceEqual, inspect, revive } from './_canonical.ts';

const FORMATS_DIR = path.join(import.meta.dirname, '..', 'conformance', 'formats');

// Mirrors conformance/formats/shared/smoke.rs (field order = layout).
const ArchivedSmokeEnum = r.taggedEnum({
  V: { a: r.u8, b: r.u32 },
  W: { a: r.u32, b: r.u64 },
  X: null,
});

const ArchivedSmokeCase = r.struct({
  a: r.u8,
  b: r.u16,
  c: r.u32,
  d: r.u64,
  e: r.i32,
  f: r.f32,
  g: r.f64,
  h: r.bool,
  s_inline: r.string,
  s_long: r.string,
  xs: r.vec(r.u32),
  opt_some: r.option(r.string),
  opt_none: r.option(r.u32),
  e_v: ArchivedSmokeEnum,
  e_w: ArchivedSmokeEnum,
  map: hashMap(r.string, r.u32),
  imap: indexMap(r.string, r.u32),
  boxed: r.box(r.u64),
});

const profiles: { name: string; fmt: RkyvFormat }[] = [
  { name: 'be', fmt: format({ endian: 'big' }) },
  { name: 'pw16', fmt: format({ pointerWidth: 16 }) },
  { name: 'pw64', fmt: format({ pointerWidth: 64 }) },
  { name: 'unaligned', fmt: format({ aligned: false }) },
];

describe('conformance formats', () => {
  for (const { name, fmt } of profiles) {
    const dir = path.join(FORMATS_DIR, `cases-${name}`);
    it(name, { skip: !existsSync(path.join(dir, 'data.bin')) }, async () => {
      const data = new Uint8Array(await readFile(path.join(dir, 'data.bin')));
      const expected = revive(JSON.parse(await readFile(path.join(dir, 'data.json'), 'utf-8')));

      const decoded = ArchivedSmokeCase.decode(data, fmt);
      assert.ok(
        conformanceEqual(decoded, expected, true),
        `decoded value differs\ndecoded: ${inspect(decoded)}\nexpected: ${inspect(expected)}`,
      );

      const reencoded = ArchivedSmokeCase.encode(decoded, fmt);
      await writeFile(path.join(dir, 'js.bin'), reencoded);
      assert.deepStrictEqual(reencoded, data, 'smoke case must re-encode byte-identically');
    });
  }
});
