/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';

export const ArchivedTinyVecData = r.struct({
  values: r.vec(r.u32),
  enabled: r.bool,
});

export type TinyVecData = r.Infer<typeof ArchivedTinyVecData>;

export default ArchivedTinyVecData;
