nmMode: hardlinks-global

nodeLinker: node-modules

npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.17.1.cjs

catalog:
  # For JS runtime comparison benchmark,
  # comparable packages are pinned to the exact version
  "capnp-es": "0.0.14"
  "cbor-x": "1.6.4"
  "protobufjs": "8.7.1"
