[package]
name = "conformance-pw64"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
rkyv = { workspace = true, features = ["bytecheck", "indexmap-2", "pointer_width_64"] }
indexmap = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.23.0"
toml = "1"
