/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import { r } from 'rkyv-js';

export const ArchivedThinVecData = r.struct({
  items: r.vec(r.u32),
  labels: r.vec(r.string),
});

export type ThinVecData = r.infer<typeof ArchivedThinVecData>;

export default ArchivedThinVecData;
