/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';

export const ArchivedVecDequeData = r.struct({
  items: r.vec(r.u32),
  name: r.string,
});

export type VecDequeData = r.Infer<typeof ArchivedVecDequeData>;

export default ArchivedVecDequeData;
