/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import { r } from 'rkyv-js';

export const ArchivedSmolStrConfig = r.struct({
  key: r.string,
  value: r.string,
  priority: r.u32,
});

export type SmolStrConfig = r.infer<typeof ArchivedSmolStrConfig>;

export default ArchivedSmolStrConfig;
