/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';
import { Coord } from './coord.ts';

export const ArchivedRemoteEvent = r.struct({
  name: r.string,
  location: Coord,
  priority: r.u32,
});

export type RemoteEvent = r.Infer<typeof ArchivedRemoteEvent>;

export default ArchivedRemoteEvent;
