/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';

export const ArchivedArrayVecBuffer = r.struct({
  data: r.vec(r.u32),
  name: r.string,
});

export type ArrayVecBuffer = r.Infer<typeof ArchivedArrayVecBuffer>;

export default ArchivedArrayVecBuffer;
