/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';

export const ArchivedPoint = r.struct({
  x: r.f64,
  y: r.f64,
});

export type Point = r.Infer<typeof ArchivedPoint>;

export const ArchivedMessage = r.taggedEnum({
  Quit: r.unit,
  Move: r.struct({ x: r.i32, y: r.i32 }),
  Write: r.struct({ _0: r.string }),
  ChangeColor: r.struct({ _0: r.u8, _1: r.u8, _2: r.u8 }),
});

export type Message = r.Infer<typeof ArchivedMessage>;

export const ArchivedGameState = r.struct({
  player_position: ArchivedPoint,
  health: r.u32,
  inventory: r.vec(r.string),
  current_message: r.option(ArchivedMessage),
});

export type GameState = r.Infer<typeof ArchivedGameState>;

export default ArchivedGameState;
