[package]
name = "conformance-unaligned"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
rkyv = { workspace = true, features = ["bytecheck", "indexmap-2", "unaligned"] }
indexmap = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.151"
base64 = "0.23.0"
toml = "1"
