/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';
import { uuid } from 'rkyv-js/lib/uuid';

export const ArchivedUuidRecord = r.struct({
  id: uuid,
  name: r.string,
  active: r.bool,
});

export type UuidRecord = r.Infer<typeof ArchivedUuidRecord>;

export default ArchivedUuidRecord;
