/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';
import { bytes } from 'rkyv-js/lib/bytes';

export const ArchivedBytesMessage = r.struct({
  payload: bytes,
  checksum: r.u32,
});

export type BytesMessage = r.Infer<typeof ArchivedBytesMessage>;

export default ArchivedBytesMessage;
