/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';

export const ArchivedArcShared = r.struct({
  shared_data: r.rc(r.string),
  local_data: r.u32,
});

export type ArcShared = r.Infer<typeof ArchivedArcShared>;

export default ArchivedArcShared;
