/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import { r } from 'rkyv-js';

export const ArchivedPoint = r.struct({
  x: r.f64,
  y: r.f64,
});

export type Point = r.infer<typeof ArchivedPoint>;

export default ArchivedPoint;
