/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';
import { btreeSet } from 'rkyv-js/lib/std-btree-set';

export const ArchivedBTreeSetData = r.struct({
  values: btreeSet(r.i64),
  label: r.string,
});

export type BTreeSetData = r.Infer<typeof ArchivedBTreeSetData>;

export default ArchivedBTreeSetData;
