/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';
import { btreeMap } from 'rkyv-js/lib/std-btree-map';

export const ArchivedBTreeMapConfig = r.struct({
  settings: btreeMap(r.string, r.u32),
  version: r.u32,
});

export type BTreeMapConfig = r.Infer<typeof ArchivedBTreeMapConfig>;

export default ArchivedBTreeMapConfig;
