/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';

export const ArchivedSmallVecData = r.struct({
  items: r.vec(r.u32),
  tags: r.vec(r.string),
});

export type SmallVecData = r.Infer<typeof ArchivedSmallVecData>;

export default ArchivedSmallVecData;
