/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';
import { hashSet } from 'rkyv-js/lib/std-hash-set';

export const ArchivedHashSetData = r.struct({
  ids: hashSet(r.string),
  count: r.u32,
});

export type HashSetData = r.Infer<typeof ArchivedHashSetData>;

export default ArchivedHashSetData;
