/**
 * Codec bindings for the conformance case types (conformance/src/types.rs),
 * generated by rkyv-js-codegen. Field order matches the Rust declaration
 * order exactly — it defines the archived layout.
 *
 * DO NOT EDIT MANUALLY — regenerate with
 * `cargo run -p conformance --bin generate`.
 */

import * as r from 'rkyv-js';
import { SipKeyedMap } from './sip-map.ts';
import { btreeMap, btreeSet } from 'rkyv-js/lib/btreemap';
import { bytes } from 'rkyv-js/lib/bytes';
import { hashMap, hashSet } from 'rkyv-js/lib/hashmap';
import { indexMap, indexSet } from 'rkyv-js/lib/indexmap';
import { uuid } from 'rkyv-js/lib/uuid';

export const ArchivedArraysTuples = r.struct({
  arr: r.array(r.u16, 4),
  arr_str: r.array(r.string, 2),
  tup: r.tuple(r.u8, r.string, r.f64),
  pair: r.tuple(r.u32, r.u32),
});

export type ArraysTuples = r.Infer<typeof ArchivedArraysTuples>;

export const ArchivedBTreeMapStr = r.struct({
  m: btreeMap(r.string, r.u32),
});

export type BTreeMapStr = r.Infer<typeof ArchivedBTreeMapStr>;

export const ArchivedBTreeMapU32 = r.struct({
  m: btreeMap(r.u32, r.string),
});

export type BTreeMapU32 = r.Infer<typeof ArchivedBTreeMapU32>;

export const ArchivedBTreeSetStr = r.struct({
  s: btreeSet(r.string),
});

export type BTreeSetStr = r.Infer<typeof ArchivedBTreeSetStr>;

export const ArchivedCompositeKey = r.struct({
  id: r.u32,
  name: r.string,
});

export type CompositeKey = r.Infer<typeof ArchivedCompositeKey>;

export const ArchivedExternalTypes = r.struct({
  id: uuid,
  payload: bytes,
  small_name: r.string,
  thin: r.vec(r.u32),
  array_vec: r.vec(r.u32),
  small_vec: r.vec(r.u32),
  tiny_vec: r.vec(r.u32),
  deque: r.vec(r.u32),
  shared: r.rc(r.string),
});

export type ExternalTypes = r.Infer<typeof ArchivedExternalTypes>;

export const ArchivedFloatSpecials = r.struct({
  nan32: r.f32,
  nan64: r.f64,
  pos_inf: r.f64,
  neg_inf: r.f32,
  pos_zero: r.f64,
  neg_zero: r.f64,
  subnormal32: r.f32,
  subnormal64: r.f64,
});

export type FloatSpecials = r.Infer<typeof ArchivedFloatSpecials>;

export const ArchivedHashMapI32 = r.struct({
  m: hashMap(r.i32, r.bool),
});

export type HashMapI32 = r.Infer<typeof ArchivedHashMapI32>;

export const ArchivedHashMapStr = r.struct({
  m: hashMap(r.string, r.u32),
});

export type HashMapStr = r.Infer<typeof ArchivedHashMapStr>;

export const ArchivedHashMapTupleKey = r.struct({
  m: hashMap(r.tuple(r.string, r.u32), r.bool),
});

export type HashMapTupleKey = r.Infer<typeof ArchivedHashMapTupleKey>;

export const ArchivedHashMapU32 = r.struct({
  m: hashMap(r.u32, r.u32),
});

export type HashMapU32 = r.Infer<typeof ArchivedHashMapU32>;

export const ArchivedHashMapU64 = r.struct({
  m: hashMap(r.u64, r.string),
});

export type HashMapU64 = r.Infer<typeof ArchivedHashMapU64>;

export const ArchivedHashSetStr = r.struct({
  s: hashSet(r.string),
});

export type HashSetStr = r.Infer<typeof ArchivedHashSetStr>;

export const ArchivedHashSetU32 = r.struct({
  s: hashSet(r.u32),
});

export type HashSetU32 = r.Infer<typeof ArchivedHashSetU32>;

export const ArchivedIndexMapStr = r.struct({
  m: indexMap(r.string, r.u32),
});

export type IndexMapStr = r.Infer<typeof ArchivedIndexMapStr>;

export const ArchivedIndexMapU32 = r.struct({
  m: indexMap(r.u32, r.string),
});

export type IndexMapU32 = r.Infer<typeof ArchivedIndexMapU32>;

export const ArchivedIndexSetStr = r.struct({
  s: indexSet(r.string),
});

export type IndexSetStr = r.Infer<typeof ArchivedIndexSetStr>;

export const ArchivedInventory = r.struct({
  items: r.vec(r.string),
  counts: hashMap(r.string, r.u32),
});

export type Inventory = r.Infer<typeof ArchivedInventory>;

export const ArchivedKitchenSinkRef = r.struct({
  id: uuid,
  name: r.string,
});

export type KitchenSinkRef = r.Infer<typeof ArchivedKitchenSinkRef>;

export const ArchivedMixedAlign = r.taggedEnum({
  V: { a: r.u8, b: r.u32 },
  W: { a: r.u32, b: r.u64 },
  X: r.u64,
  Y: null,
});

export type MixedAlign = r.Infer<typeof ArchivedMixedAlign>;

export const ArchivedOptions = r.struct({
  none_int: r.option(r.u32),
  some_int: r.option(r.u32),
  none_str: r.option(r.string),
  some_str: r.option(r.string),
  nested: r.option(r.option(r.u8)),
  nested_none: r.option(r.option(r.u8)),
});

export type Options = r.Infer<typeof ArchivedOptions>;

export const ArchivedPoint = r.struct({
  x: r.f64,
  y: r.f64,
});

export type Point = r.Infer<typeof ArchivedPoint>;

export const ArchivedPointers = r.struct({
  boxed: r.box(r.string),
  boxed_int: r.box(r.u64),
  rc: r.rc(r.string),
  weak_dead: r.weak(r.u32),
});

export type Pointers = r.Infer<typeof ArchivedPointers>;

export const ArchivedPrimitives = r.struct({
  a: r.u8,
  b: r.i8,
  c: r.u16,
  d: r.i16,
  e: r.u32,
  f: r.i32,
  g: r.u64,
  h: r.i64,
  i: r.f32,
  j: r.f64,
  k: r.bool,
  l: r.char,
});

export type Primitives = r.Infer<typeof ArchivedPrimitives>;

export const ArchivedSharedRc = r.struct({
  a: r.rc(r.string),
  b: r.rc(r.string),
});

export type SharedRc = r.Infer<typeof ArchivedSharedRc>;

export const ArchivedSipHashedMap = r.struct({
  m: SipKeyedMap,
});

export type SipHashedMap = r.Infer<typeof ArchivedSipHashedMap>;

export const ArchivedStrings = r.struct({
  empty: r.string,
  one: r.string,
  seven: r.string,
  eight: r.string,
  nine: r.string,
  sixty_three: r.string,
  sixty_four: r.string,
  long: r.string,
  multibyte: r.string,
  astral: r.string,
});

export type Strings = r.Infer<typeof ArchivedStrings>;

export const ArchivedStructKey = r.struct({
  id: r.u32,
  tag: r.string,
});

export type StructKey = r.Infer<typeof ArchivedStructKey>;

export const ArchivedHashMapStructKey = r.struct({
  m: hashMap(ArchivedStructKey, r.u32),
});

export type HashMapStructKey = r.Infer<typeof ArchivedHashMapStructKey>;

export const ArchivedTupleVariants = r.taggedEnum({
  Color: { _0: r.u8, _1: r.u8, _2: r.u8 },
  Wrap: r.string,
  Empty: null,
});

export type TupleVariants = r.Infer<typeof ArchivedTupleVariants>;

export const ArchivedKitchenSink = r.struct({
  id: uuid,
  name: r.string,
  position: ArchivedPoint,
  health: r.option(r.u32),
  state: ArchivedMixedAlign,
  inventory: ArchivedInventory,
  tags: indexSet(r.string),
  settings: btreeMap(r.string, r.i64),
  history: r.vec(ArchivedTupleVariants),
  parent: r.option(r.box(ArchivedKitchenSinkRef)),
});

export type KitchenSink = r.Infer<typeof ArchivedKitchenSink>;

export const ArchivedUnitOnly = r.taggedEnum({
  A: null,
  B: null,
  C: null,
});

export type UnitOnly = r.Infer<typeof ArchivedUnitOnly>;

export const ArchivedEnumCases = r.struct({
  unit: ArchivedUnitOnly,
  mixed_v: ArchivedMixedAlign,
  mixed_w: ArchivedMixedAlign,
  mixed_x: ArchivedMixedAlign,
  mixed_y: ArchivedMixedAlign,
  tuple_variant: ArchivedTupleVariants,
  wrap: ArchivedTupleVariants,
  in_option: r.option(ArchivedMixedAlign),
});

export type EnumCases = r.Infer<typeof ArchivedEnumCases>;

export const ArchivedVecs = r.struct({
  empty: r.vec(r.u32),
  one: r.vec(r.u32),
  many: r.vec(r.u32),
  strings: r.vec(r.string),
  structs: r.vec(ArchivedPoint),
  nested: r.vec(r.vec(r.u16)),
});

export type Vecs = r.Infer<typeof ArchivedVecs>;
