/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';

export const ArchivedMessage = r.taggedEnum({
  Quit: r.unit,
  Move: r.struct({ x: r.i32, y: r.i32 }),
  Write: r.struct({ _0: r.string }),
  ChangeColor: r.struct({ _0: r.u8, _1: r.u8, _2: r.u8 }),
});

export type Message = r.Infer<typeof ArchivedMessage>;

export default ArchivedMessage;
