/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import * as r from 'rkyv-js';
import { indexMap, indexSet } from 'rkyv-js/lib/indexmap';

export const ArchivedIndexMapConfig = r.struct({
  settings: indexMap(r.string, r.u32),
  version: r.u32,
});

export type IndexMapConfig = r.Infer<typeof ArchivedIndexMapConfig>;

export default ArchivedIndexMapConfig;
