/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import { r } from 'rkyv-js';
import { indexMap, indexSet } from 'rkyv-js/lib/indexmap';

export const ArchivedIndexMapConfig = r.struct({
  settings: indexMap(r.string, r.u32),
  version: r.u32,
});

export type IndexMapConfig = r.infer<typeof ArchivedIndexMapConfig>;

export default ArchivedIndexMapConfig;
