/**
 * Auto-generated by rkyv-js-codegen
 * DO NOT EDIT MANUALLY
 */

import { r } from 'rkyv-js';
import { indexMap, indexSet } from 'rkyv-js/lib/indexmap';

export const ArchivedIndexSetTags = r.struct({
  tags: indexSet(r.string),
  count: r.u32,
});

export type IndexSetTags = r.infer<typeof ArchivedIndexSetTags>;

export default ArchivedIndexSetTags;
